name: SSH and Git Pull

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: SSH and Git Pull
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
        if [ ! -d "Allnewsmr-API/" ]; then
          git clone https://github.com/SheikhElMoctarG/Allnewsmr-API.git 
        else
          cd Allnewsmr-API
          git pull origin main
        fi
        docker build -t allnewsmr-api .
        if [ $(docker ps -a -q -f name=allnewsmr-api) ]; then
          docker stop allnewsmr-api || true
          docker rm allnewsmr-api || true
        fi
        if sudo lsof -i :3000 | grep LISTEN; then
          echo "Port 3000 is in use. Stopping and removing the previous container."
          if [ $(docker ps -a -q -f name=allnewsmr-api) ]; then
            docker stop allnewsmr-api || true
            docker rm allnewsmr-api || true
          fi
        fi
        # docker run -d --name allnewsmr-api -p 3000:3000 allnewsmr-api
        EOF
